### ISSUE TITLE
Optimize the codebase

### ISSUE THREAD

**Issue by rahulsain** [rahulsain/MemeIt#9]
All the majority of the code is currently written in MainActivity.kt , it would be helpful that a proper package should be created for each classes

**Comment by mjmadhur** [comment]
I want to work on this and add some more features to app

**Comment by rahulsain** [comment]
Sure, go ahead.


Just discuss what all new features you are currently thinking of?

**Comment by mjmadhur** [comment]
I want to make the ui better and add some differnetiating colors/design to the buttons .

**Comment by rahulsain** [comment]
Okay, and what about the new feature?

**Comment by mjmadhur** [comment]
Just ui modifications and adding a splash screen.

**Comment by rahulsain** [comment]
Well that's enhancements, ok you can proceed

**Comment by mjmadhur** [comment]
Awesome, thanks!
I will do it and make a pull request by tonight.

**Comment by mjmadhur** [comment]
Mate i did pull request plss go through it and approove if u like it.
 Username:mjmadhur

**Comment by mjmadhur** [comment]
Can uh Merge the pr
